// Copyright 2011 Yandex

#ifndef LTR_DATA_UTILITY_NOMINAL_FEATURE_HANDLER_H_
#define LTR_DATA_UTILITY_NOMINAL_FEATURE_HANDLER_H_

#include <boost/shared_ptr.hpp>

#include <vector>
#include <map>
#include <string>

#include "ltr/data/feature_info.h"

using std::string;
using std::vector;
using std::map;

namespace ltr {
namespace io_utility {
  enum NominalFeatureType {
    NUMERIC,
    NOMINAL,
    BOOLEAN,
    META,
    CLASS,
  };
  /**
   * @section DESCRIPTION
   * This struct contains information about features. Generated by IParser.
   */
  struct NominalFeatureInfo {
    public:
      map<int, NominalFeatureType> feature_type_;
      map<int, string> feature_name_;
      map<int, vector<string> > feature_values_;
  };
  /**
   * @section DESCRIPTION
   * This class allows to convert string features into vector of double
   */
  class NominalFeatureHandler {
    public:
      typedef boost::shared_ptr<NominalFeatureHandler> Ptr;
      /**
       * Function to initialize handler.
       * @param info - information about features.
       */
      virtual void init(const NominalFeatureInfo& info) = 0;
      /**
       * Function returns FeatureInfo object.
       * Information about features to save into data set
       */
      virtual const FeatureInfo& featureInfo() = 0;
      /**
       * Function processes features.
       * @param features - map of features to process
       * @param result - link to vector to save resulting features in.
       * @code
       * vector<double> result;
       * handler->process(features, &result);
       * @endcode
       */
      virtual void process(map<int, string> features,
                           vector<double>* result) = 0;
      virtual ~NominalFeatureHandler() {}
  };

  class RemoveHandler : public NominalFeatureHandler {
    public:
      RemoveHandler();
      void init(const NominalFeatureInfo& info);
      void process(map<int, string> features, vector<double>* result);
      const FeatureInfo& featureInfo() {return feature_info_;}
    private:
      FeatureInfo feature_info_;
      map<int, int> feature_id;
      int max_feature_id;
      int nominal_cnt;
  };
};
};

#endif  // LTR_DATA_UTILITY_NOMINAL_FEATURE_HANDLER_H_
